-- first remove any foreign key constraints
alter table if exists folders
drop column id;

--drop tables in reverse order to make sure we have clean data bases to work with
drop table if exists folders;

--create the project table that is the most independent table
create table folders (
    id integer primary key generated by default as identity,
    folder_name text not null
)


--add foreign keys after I make the other tables