--create the project table that is the most independent table
create table folders (
    id integer primary key generated by default as identity,
    name text not null
);


--add foreign keys after I make the other tables