

--drop tables to make sure the tables will be clean
drop table if exists notes;

--create the project table that is the most independent table
create table notes (
    id integer primary key generated by default as identity,
    note_name text not null,
    content text not null,
    date_added TIMESTAMPTZ default now() not null
)
