--create the project table that is the most independent table
create table notes (
    id integer primary key generated by default as identity,
    name text not null,
    content text not null,
    modified TIMESTAMPTZ default now() not null
)
